name: samuelosmith
favicon: null
layout_spectrum: 0.4850066597573459
typography_spectrum: 0.419321627356112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.21469118539243937
  lightness: 0.16853002551943064
  saturation: 0.3904959848150611
  rhythmicContrast: 0.4281982802785933
purpose: []
