name: samuelosmith
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232221'
    - '#f58025'
    - '#f3f3f3'
    - '#7f4b25'
    - '#9d9fa1'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
